- name: Set K8S control-plane node hostname fact
  ansible.builtin.set_fact:
    hostname_fact: "{{ ansible_fqdn }}"
  when: inventory_hostname == "k8scp"

- name: Configure Kubernetes cluster
  ansible.builtin.blockinfile:
    path: /etc/kubernetes/kubeadm-config.yaml
    create: true
    mode: '0644'
    owner: root
    group: root
    block: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      kubernetesVersion: "{{ kubernetes_ver }}"
      controlPlaneEndpoint: "{{ hostvars['k8scp'].ansible_host }}:6443"
      networking:
        podSubnet: 192.168.0.0/16
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external

- name: Initialize the Kubernetes cluster
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml --node-name="{{ ansible_fqdn }}"
    executable: /bin/bash
  register: kubeadm_init_result
  changed_when: "'Your Kubernetes control-plane has initialized successfully!' in kubeadm_init_result.stdout"
  failed_when: kubeadm_init_result.rc != 0

- name: Create .kube directory
  become: true
  become_user: ubuntu
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    mode: "0755"

- name: Copy admin.conf to .kube directory
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: true
    mode: preserve
    owner: ubuntu

- name: Clone the AWS Cloud Controller Manager
  ansible.builtin.git:
    repo: https://github.com/kubernetes/cloud-provider-aws.git
    dest: "/home/ubuntu/cloud-provider-aws"
    version: "{{ cloud_aws_ver }}"

- name: Deploy AWS Cloud Controller
  become: true
  become_user: ubuntu
  ansible.builtin.command: kubectl apply -k .
  args:
    chdir: "/home/ubuntu/cloud-provider-aws/examples/existing-cluster/base/"
  register: aws_ccm_output
  changed_when: "'configured' in aws_ccm_output.stdout or 'created' in aws_ccm_output.stdout"

- name: Deploy AWS EBS CSI driver
  become: true
  become_user: ubuntu
  ansible.builtin.command: >
    kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-{{ csi_driver_ver }}"
  register: ebs_csi_output
  changed_when: "'created' in ebs_csi_output.stdout or 'configured' in ebs_csi_output.stdout"

- name: Intall package "bash-completion"
  ansible.builtin.apt:
    name: bash-completion
    state: present

- name: Enable kubectl bash completion for ubuntu user
  become: true
  become_user: ubuntu
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'source <(kubectl completion bash)'
    insertafter: EOF
    state: present

- name: Download Helm installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get-helm.sh
    mode: "0700"

- name: Run Helm installation script
  ansible.builtin.command:
    cmd: /tmp/get-helm.sh
  changed_when: false

- name: Add Cilium Helm repository
  ansible.builtin.command: helm repo add cilium https://helm.cilium.io/
  register: cilium_repo_add
  failed_when: cilium_repo_add.rc != 0 and '"exists" not in cilium_repo_add.stderr'
  changed_when: '"has been added" in cilium_repo_add.stdout'

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  changed_when: false

- name: Generate cilium.yaml
  ansible.builtin.shell:
    cmd: |
        set -o pipefail
        helm template cilium cilium/cilium --version "{{ cilium_ver }}" --namespace kube-system > /etc/kubernetes/cilium-cni.yaml
    executable: /bin/bash
  changed_when: false

- name: Set the pod network in Cilium
  ansible.builtin.replace:
    path: /etc/kubernetes/cilium-cni.yaml
    after: 'cluster-pool-ipv4-cidr:'
    regexp: '["][0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/[0-9]["]+$'
    replace: '"192.168.0.0/16"'

- name: Install pod network
  become: true
  become_user: ubuntu
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/cilium-cni.yaml
  register: cilium_apply_output
  changed_when: "'created' in cilium_apply_output.stdout or 'configured' in cilium_apply_output.stdout"

- name: Extract CERT_HASH
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt \
      | openssl rsa -pubin -outform der 2>/dev/null \
      | openssl dgst -sha256 -hex | sed 's/^.* //'
    executable: /bin/bash
  register: cert_hash
  changed_when: false

- name: Extract token
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      kubeadm token list -o json | jq -r '.token' | head -1
    executable: /bin/bash
  register: token
  changed_when: false

- name: Set cert_hash as ansible.builtin.set_fact
  ansible.builtin.set_fact:
    cert_hash_fact: "{{ cert_hash.stdout_lines[0] | trim }}"

- name: Set token_hash as ansible.builtin.set_fact
  ansible.builtin.set_fact:
    token_fact: "{{ token.stdout_lines[0] | trim }}"

- name: Allow pod scheduling on the control plane
  become_user: ubuntu
  ansible.builtin.command:
    cmd: kubectl taint node "{{ ansible_fqdn }}" node-role.kubernetes.io/control-plane:NoSchedule-
  when: kubernetes_schedule_pods_control_plane | bool
  changed_when: false

- name: Add metrics-server Helm repo
  become_user: ubuntu
  ansible.builtin.command:
    cmd: helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
  register: add_repo
  changed_when: false

- name: Update Helm repos
  become_user: ubuntu
  ansible.builtin.command:
    cmd: helm repo update
  register: helm_update
  changed_when: "'Successfully got an update' in helm_update.stdout"

- name: Install Metrics Server using Helm with kubeconfig
  become_user: ubuntu
  ansible.builtin.command:
    cmd: >
      helm upgrade --install metrics-server metrics-server/metrics-server
      --namespace kube-system
      --set args={--kubelet-insecure-tls,--kubelet-preferred-address-types=InternalIP\,Hostname\,ExternalIP}
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  changed_when: false
