---
- name: Install Kubernetes prerequisites
  hosts: all
  become: true
  roles:
    - k8s-prerequisites

- name: Install and configre Kubernetes master node
  hosts: masters
  become: true
  roles:
    - k8s-master

- name: Install and configure Kubernetes worker nodes
  hosts: workers
  become: true
  roles:
    - k8s-worker
