# Define Kubernetes version
kubernetes_ver: "1.30.1"
# Define Kubernetes repository version
kuberepo_ver: "1.30"
# Define kubeadm version
kubeadm_ver: "1.30.1-1.1"
# Define kubelet version
kubelet_ver: "1.30.1-1.1"
# Define kubectl version
kubectl_ver: "1.30.1-1.1"
# Define cilium version
cilium_ver: "1.16.1"
# Define cloud aws provider version
cloud_aws_ver: "v1.32.2"
# Define csi driver version
csi_driver_ver: "1.45"
# Enable pod scheduling on the control plane.
kubernetes_schedule_pods_control_plane: "true"
